#!/bin/bash
set -e

cd -- "$(dirname -- "$0")"

declare -a ASSETS=(browser.html)

for asset in "${ASSETS[@]}"; do
    var="$(printf "$asset" | tr -c 'a-zA-Z' '_')"
    bin2go -pkg=main -in="$asset" -out="$asset.go" "$var"
done
echo go run browser.go "${ASSETS[@]/%/.go}" "$@"
exec go run browser.go "${ASSETS[@]/%/.go}" "$@"
