language: go
go:
  - tip
before_install:
  - go get github.com/mattn/gom
script:
  - $HOME/gopath/bin/gom install
  - $HOME/gopath/bin/gom test ./_vendor/src/github.com/cloudspace/go-thrust/
  - $HOME/gopath/bin/gom test ./_vendor/src/github.com/cloudspace/go-thrust/lib/...
